### PR TITLE
Fixed : Meet the Founder Section in not working properly on hover and Social Icons 

### LINKED ISSUE #192: [Feature]:  Meet the Founder Section in not working properly on hover
### Is your feature request related to a problem? Please describe.

Meet the Founder Section in not working properly on hovering .
comm1
 

### Describe the solution you'd like

We should add hover transition to make it more smooth 

### Describe alternatives you've considered

We can use transition property to look more better.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Amishakumari544**
# Description

Fixes #192 
# Checklist:

- [x] Fixed the founder card
- [x] Added hover in the social icons 
- [x] Fixed alignment of social icons
- [x] Changed the text **bootstrap** made to **Community** added link

# Screenshot (91)

### CODE REVIEW

**Review by harkiratsm — APPROVED** [review]

**Comment by harkiratsm** [comment]
The changes on footer was not required - what u say  @kaiwalyakoparkar

**Comment by Amishakumari544** [comment]
No kawailya told me to improve the social icons And I am also thinking that its not looking good at hover

**Comment by kaiwalyakoparkar** [comment]
@Amishakumari544 I was talking about

**Comment by Amishakumari544** [comment]
ok so , Should remove the changes of footer  which I did? @kaiwalyakoparkar

**Pull request closed without merging**
