### PR TITLE
for smooth accessibility added cursor-pointer

### PR DESCRIPTION
**Pull request by roopeshsn**
# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] User Interface

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have ```npm run format``` before committing
- [x] I replicated the UI with the Design 

# ScreenShots (if any)

### CODE REVIEW

**Review by vikasganiga05 — COMMENTED** [review]
Remove the unwanted files from the commit.

**Review by vikasganiga05 — CHANGES_REQUESTED** [review]
Please remove the `package-lock.json` and `yarn.lock` files from the commit.

**Comment by roopeshsn** [comment]
I did changes only in the "Courses.jsx" file. I don't know how the extra code was added in the package-lock.json and yarn.lock

**Comment by roopeshsn** [comment]
Could you guide me on how to remove the files from the commit

**Comment by vikasganiga05** [comment]
Yeah! sure, This blog post may help you - [How to remove/Undo a Commit from your PR](https://anush-venkatakrishna.medium.com/how-to-remove-undo-a-commit-from-your-pr-65e2e4e195af)

**Pull request closed without merging**
