### PR TITLE
fixes the css

### LINKED ISSUE #178: [Bug]: The Cards on the home page changes radius on hover (looks unprofessional)
### Describe the bug

The cards look a bit unprofessional due to unnecessary change in radius and irregular margin between text

### To Reproduce

Home Page

### Expected Behavior

A bit of change in colour and a uniform margin between texts in the card section

### Screenshot/ Video

Screenshot from 2021-10-01 16-37-16

### Desktop (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KamalSinghKhanna**
# Description
Fixes #178 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have ```npm run format``` before commiting
- [ ] I replicated the UI with the Design 

# ScreenShots (if any)

### CODE REVIEW

**Comment by KamalSinghKhanna** [comment]
@Soham041201  can you review this.

**Comment by Soham041201** [comment]
Actually I have already raised the PR for this :) Before starting to work on the issue, make sure to check in the issue discussion forum if anyone is working on that issue or not. PS: Also add screenshots

**Comment by KamalSinghKhanna** [comment]
sorry about that but I didn't see any PR link to this issue.

**Comment by Soham041201** [comment]
> sorry about that but I didn't see any PR link to this issue.

There was a typo from my side in tagging the issue :)

**Pull request closed without merging**
