### PR TITLE
Fixed Dark mode button not working

### LINKED ISSUE #115: Dark mode button not working

### PR DESCRIPTION
**Pull request by Shivansh-yadav13**
- fixes #115

### CODE REVIEW

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
screenshots

**Comment by Shivansh-yadav13** [comment]
> screenshots
c2
c4
c6
c8

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
the header does not look good. the community classroom logo isnt working. please change color of header to something light.

**Comment by Shivansh-yadav13** [comment]
@kunal-kushwaha 
Can we use a different image for the dark theme?


ss

**Review by kunal-kushwaha — APPROVED** [review]

**Comment by kunal-kushwaha** [comment]
@Shivansh-yadav13 I merged this PR. The changes look good. Can you please make another PR and change the logo for dark theme?

**Comment by Shivansh-yadav13** [comment]
> @Shivansh-yadav13 I merged this PR. The changes look good. Can you please make another PR and change the logo for dark theme?

Done  check  #143

**Pull request merged**
