### PR TITLE
Updated Footer Design / Background color

### PR DESCRIPTION
**Pull request by riyasavant**
- Updated Background color to make it look more soothing
- Updated the footer design to make it look minimalistic #117

### CODE REVIEW

**Comment by riyasavant** [comment]
footer-cc

**Review by daredevilteja — CHANGES_REQUESTED** [review]
Remove the bottom 'Designed by BootstrapMade' and then add Contact Us in the footer

**Comment by riyasavant** [comment]
Updated the changes
footer-cc2

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
only change the color and nothing else

**Comment by riyasavant** [comment]
Screenshot (354)

**Comment by riyasavant** [comment]
> only change the color and nothing else

Done.

**Comment by kunal-kushwaha** [comment]
fixed already

**Pull request closed without merging**
