### PR TITLE
Added Github icon in footers of all pages

### LINKED ISSUE #187: [Bug]: Add Github icon for commclassroom github page in footer
### Describe the bug

In the footer section, there is Instagram, Twitter, Linkedin, Discord, youtube icon but it would be good if there is a github icon.
The github icon will be connected to https://github.com/commclassroom

### To Reproduce

Screenshot from 2021-10-01 19-17-58

### Expected Behavior

Github icon at the rightmost side
Screenshot from 2021-10-01 19-20-16

### Screenshot/ Video

_No response_

### Desktop (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rwiteshbera**
# Description
Fixes #187 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] User Interface
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I replicated the UI with the Design 

# ScreenShots (if any) 

Hover Effect

Screenshot from 2021-10-01 21-38-43

### CODE REVIEW

**Comment by rwiteshbera** [comment]
@kaiwalyakoparkar Please review my PR

**Comment by harkiratsm** [comment]
image

Add to other pages as well

**Comment by rwiteshbera** [comment]
@harkiratsm I have added on all other pages. Check my PR once.

**Comment by harkiratsm** [comment]
@rwiteshbera When we access the course , the footer is like
image
do makes changes on this page too . 😄

**Pull request closed without merging**
