### PR TITLE
align the social icons and added transition in the team section

### LINKED ISSUE #192: [Feature]:  Meet the Founder Section in not working properly on hover
### Is your feature request related to a problem? Please describe.

Meet the Founder Section in not working properly on hovering .
comm1
 

### Describe the solution you'd like

We should add hover transition to make it more smooth 

### Describe alternatives you've considered

We can use transition property to look more better.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Amishakumari544**
Fixes #192 

@harkiratsm  Please review the PR

### CODE REVIEW

**Comment by Amishakumari544** [comment]
Screenshot (96)

**Comment by harkiratsm** [comment]
1)On Hover color of social icons are same , change that . 
2)Checkout the transition in dark Mode & make the require changes .

**Comment by Amishakumari544** [comment]
> 1)On Hover color of social icons are same , change that . 2)Checkout the transition in dark Mode & make the require changes .

You are talking of which social icons can you please mark? I have to only make the social icons in the center nothing else

**Comment by Amishakumari544** [comment]
> > 1)On Hover color of social icons are same , change that . 2)Checkout the transition in dark Mode & make the require changes .
> 
> You are talking about which social icons can you please mark? I have to only make the social icons in the center nothing else

**Review by harkiratsm — APPROVED** [review]

**Comment by harkiratsm** [comment]
LGTM 🚀

**Comment by Amishakumari544** [comment]
thank you :)

**Pull request merged**
