### PR TITLE
Adding section components: FAQ, Sponsors, Inspire, Team

### PR DESCRIPTION
**Pull request by yashsehgal**
Adding the following sections in this PR

- FAQ
- What makes us so good?
- Sponsors
- Team

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
Perhaps you can make it easier to review by adding a few screenshots or screen recordings.

**Comment by siddhant-khisty** [comment]
@AnuragThePathak, Kaiwalya is working on something to make reviews easier

**Comment by AnuragThePathak** [comment]
Oh, that's awesome, ig it's going to be the preview of the site resulting from the commits in the PR.

**Comment by kaiwalyakoparkar** [comment]
@yashsehgal there are conflicts please resolve if still valid

**Comment by yashsehgal** [comment]
> @yashsehgal there are conflicts please resolve if still valid. Else close the PR

Hey @kaiwalyakoparkar 
Sorry for the delay, I will pull the changes and resolved the merge conflicts, but this PR had implementation of the `v2` UI thus I believe I should create a new PR for the new sections from `v3`

**Pull request closed without merging**
