### PR TITLE
Added a FAQ Section

### PR DESCRIPTION
**Pull request by akash-kumar44**
@kunal-kushwaha, @samjn08, I added a FAQ section and wrote 4 questions. We can edit it and can change the question, answers. This is just an idea if you like it, then we can improve this section.

Thank you !!

### CODE REVIEW

**Comment by akash-kumar44** [comment]
Screenshot (62)

**Comment by akash-kumar44** [comment]
Screenshot (62)

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
please take data from json instead of hardcoding

**Comment by akash-kumar44** [comment]
Ok will do

**Pull request closed without merging**
