### PR TITLE
Re-designed the buttons

### PR DESCRIPTION
**Pull request by Salonee-Jain**
- [Learn More] and [Coming Soon] buttons were re-designed to outline buttons 
-  Gradient colors were added to [Explore More Courses] button

### CODE REVIEW

**Comment by Salonee-Jain** [comment]
Yes I can share the Screenshots

**Comment by Salonee-Jain** [comment]
## Outline Buttons
comm2
comm3

## Gradient Button
comm

**Comment by Salonee-Jain** [comment]
@YashKumarVerma Can I get an update on this?

**Comment by kunal-kushwaha** [comment]
@Salonee-Jain I dont see any files changes, can you please check?

**Comment by Vyvy-vi** [comment]
@Salonee-Jain It looks like you re-wrote the branch in https://github.com/commclassroom/commclassroom/pull/12/commits/b15ca0dd5e3a45683f2303757a02ac82e8c5bf0f

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
fix commits

**Pull request closed without merging**
