### PR TITLE
Added Navbar Functionality[React]

### LINKED ISSUE #293: NavBar Improvement [React]
### Is your feature request related to a problem? Please describe.

1) Current Navbar is not functional , try to make it functional 
2) Make it sticky also elevate the navbar so it looks cool  😄 .
3) We are using **tailwind css** , (so make sure you guys are using it in the Project)
4) Have Fun 😄 making this .
5) Current Navbar 👇 

image

Try to make it 👇 

image

(*Ignore the Search Bar for Now )

### Additional context

Happy Hacking 🚀 !

### PR DESCRIPTION
**Pull request by AbhinavMV**
# Description

Made Navbar styling and functionality changes

closes #293 
## Type of change
Added react-scroll package to add functionality and used tailwind classes to add styling

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] User Interface
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have ```npm run format``` before committing
- [x] I replicated the UI with the Design 

## Screenshots (if applicable) 
image

### CODE REVIEW

**Comment by AbhinavMV** [comment]
Hi @harkiratsm,
I have made the changes to the navbar (styling and functionality).
Please let me know if anything else needs to be done in this.

**Comment by harkiratsm** [comment]
For the ```home```  you should also add a scroll effect . 😄

**Comment by AbhinavMV** [comment]
scroll effect? 
Could you ellaborate or Could you share an example? Like any other website with this feature?

**Comment by harkiratsm** [comment]
> scroll effect? Could you ellaborate or Could you share an example? Like any other website with this feature?

Just taking about like u did for ```aboutus``` button can you also do for ```home``` button too .

**Comment by AbhinavMV** [comment]
Is there a specific home page on the website? 
Even in the figma design i can see pages for courses and about us but not Home.
Please let me which page is home will add the effect.🙂

**Comment by harkiratsm** [comment]
this is the home page ```commclassroom/design/light-theme/hero.png```

**Comment by AbhinavMV** [comment]
> This is the home page `commclassroom/design/light-theme/hero.png` [here](https://github.com/commclassroom/commclassroom/blob/development/design/light-theme/hero.png) 😄

Added it. 👍
Let me know if anything else is needed. 😄

**Comment by harkiratsm** [comment]
LGTM 🚀

**Pull request merged**
