### PR TITLE
Footer background color updated to match the theme

### LINKED ISSUE #117: Change footer UI to match with the rest of the theme
Screenshot 2021-09-26 at 4 28 19 PM

### PR DESCRIPTION
**Pull request by harshmathurx**
Fixes #117

### CODE REVIEW

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
screenshots please

**Comment by harshmathurx** [comment]
my bad, here it is 
image

**Comment by kunal-kushwaha** [comment]
I dont see any difference

**Comment by harshmathurx** [comment]
give me an idea how you want it to be like

**Pull request closed without merging**
