### PR TITLE
Update issue templates

### LINKED ISSUE #129: Add issues template
As of now, there is just a normal issue opening method. We would like to have issue templates namely `Bug`, `Feature`, `Other` in the most recent `.yml` format

### PR DESCRIPTION
**Pull request by Harshal0902**
# Description
Fixes #129 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] User Interface
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have ```npm run format``` before commiting
- [ ] I replicated the UI with the Design 

# ScreenShots (if any)

### CODE REVIEW

**Comment by harkiratsm** [comment]
@Harshal0902 I think we require a ```.yml``` format not ```.md``` , am I right @kaiwalyakoparkar

**Comment by Harshal0902** [comment]
@harkiratsm thank you for letting me know, I will correct it now

**Review by harkiratsm — COMMENTED** [review]
Good To Go

**Review by harkiratsm — APPROVED** [review]

**Comment by harkiratsm** [comment]
LGTM 🚀

**Pull request merged**
