### PR TITLE
#25 Created React structure and added routing features

### PR DESCRIPTION
**Pull request by daredevilteja**
Created the base project structure in react. Added the routing capabilities. Created individual components in which people can contribute.

### CODE REVIEW

**Comment by kunal-kushwaha** [comment]
@daredevilteja screenshots?

**Comment by daredevilteja** [comment]
> @daredevilteja screenshots? 

Shall I post the website screenshot

**Comment by daredevilteja** [comment]
> @daredevilteja screenshots?

@kunal-kushwaha This is how it looks
commclassroom
The links in the top bar are clickable and by clicking the link the route would change appropriately. People can contribute easily for the pages mentioned in the links.

**Comment by harkiratsm** [comment]
Thanks for showing interest , It has already been built .

**Pull request closed without merging**
