### PR TITLE
Updated design images

### PR DESCRIPTION
**Pull request by shreyanshmalvya**
Updated the design images and updated the readme to make designs more accessible

### CODE REVIEW

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
please add screenshots

**Comment by shreyanshmalvya** [comment]
@kunal-kushwaha Screenshots are added in respective theme folders and to make them easily accessible, I've attached the same in the readme.
Should I drop images directly into the design folder and remove them from readme?

**Comment by shreyanshmalvya** [comment]
Here is a screenshot of changes I made (folder wise themes and updated readme)
image
image
image
image

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
