### PR TITLE
feat: Disable blank issues

### PR DESCRIPTION
**Pull request by Panquesito7**
# Description

- Disable blank issues.
  - We already have a generic (other) issue template, so we can disable the blank issues with no problems.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] User Interface
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have ```npm run format``` before commiting
- [ ] I replicated the UI with the Design

### CODE REVIEW

**Comment by harkiratsm** [comment]
Can you enable the issues tab so that I can check it .

**Comment by harkiratsm** [comment]
I am still able to open a blank a issue 😄 
image

**Comment by Panquesito7** [comment]
> I am still able to open a blank a issue 😄 image

Ahh, I think I know why 😅 it must be merged into the `main` branch.
You can check the [Classroom Monitor Bot](https://github.com/commclassroom/classroom-monitor-bot) repository for that. 🙂

**Review by harkiratsm — APPROVED** [review]

**Comment by harkiratsm** [comment]
LGTM 🚀

**Pull request merged**
