### PR TITLE
Added pull request template.

### PR DESCRIPTION
**Pull request by siddhi-244**
Fixed : #130

### CODE REVIEW

**Comment by harkiratsm** [comment]
@siddhi-244  refer to ```development``` branch PR template & make changes to this .

**Comment by siddhi-244** [comment]
> @siddhi-244 refer to `development` branch PR template & make changes to this .

Should I use all of that?

**Comment by harkiratsm** [comment]
Yes u Can

**Comment by siddhi-244** [comment]
> Yes

Done.

**Review by harkiratsm — APPROVED** [review]

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
